image: python:3.6-alpine

stages:
  - deploy

before_script:
   - apk add gcc
   - apk add libc-dev
   - apk add libffi-dev
   - pip install twine
   - python setup.py sdist
   - python setup.py version
deploy_staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  script:
    - twine upload --repository-url $PYPRI_REPOSITORY_URL dist/*
